name: Auto Update README with Project Structure

on:
  push:
    paths:
      - '**'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tree (for structure display)
        run: sudo apt-get install tree

      - name: Generate structure markdown
        run: |
          echo "## ShellSmith Files Structure" > structure.md
          echo "\`\`\`" >> structure.md
          tree -a -I '.git|node_modules|__pycache__' >> structure.md
          echo "\`\`\`" >> structure.md

      - name: Insert structure into README
        run: |
          # Define the markers
          START="## ShellSmith Files Structure"
          END="## "  # Next section or end of file

          # Split the README into three parts:
          # 1. Before the structure block
          # 2. The new structure
          # 3. After the structure block (if any)

          awk -v s="$START" -v e="$END" '
            BEGIN {in_block=0}
            $0 ~ s {print; print "```"; system("tree -a -I \".git|node_modules|__pycache__\""); print "```"; in_block=1; next}
            in_block && $0 ~ e {in_block=0}
            !in_block
          ' README.md > new_readme.md

          mv new_readme.md README.md


      - name: Commit & push if README changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update README with latest project structure"
          git push
