name: Update README with Project Structure

on:
  push:
    paths:
      - '**'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tree if missing
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Generate project structure
        run: |
          echo "## Project Structure" > structure.md
          echo '```' >> structure.md
          tree -I '.git|node_modules|__pycache__' -a >> structure.md
          echo '```' >> structure.md

      - name: Update README.md
        run: |
          if grep -q "## Project Structure" README.md; then
            awk '
              BEGIN {section=0}
              /^## Project Structure/ {print; section=1; next}
              /^## / && section {section=0}
              !section
            ' README.md > temp_readme.md
          else
            cat README.md > temp_readme.md
          fi
          cat temp_readme.md structure.md > new_readme.md
          mv new_readme.md README.md
          rm temp_readme.md structure.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "Update project structure in README"
          git push
