name: Auto Update README with Project Structure

on:
  push:
    paths:
      - '**'
      - '!README.md'
  pull_request:
    paths:
      - '**'
      - '!README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tree (for structure display)
        run: sudo apt-get install tree

      - name: Insert updated structure into README
        run: |
          # Generate tree output and indent it for markdown
          STRUCTURE=$(tree -a -I '.git|node_modules|__pycache__' | sed 's/^/    /')

          # Inject the tree structure between the markers
          awk -v struct="$STRUCTURE" '
            BEGIN {inside=0}
            /<!-- START STRUCTURE -->/ {
              print
              print "```"
              print struct
              print "```"
              inside=1
              next
            }
            /<!-- END STRUCTURE -->/ {
              inside=0
              print
              next
            }
            !inside
          ' README.md > README_TMP.md

          mv README_TMP.md README.md

      - name: Commit & push if README changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "📁 Auto-update README with latest project structure"
          git push
